/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-05-19 18:07:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.seat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.Seat;
import model.User;

public final class list_002dseat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/common/header.jspf", Long.valueOf(1779189206000L));
    _jspx_dependants.put("/jsp/common/footer.jspf", Long.valueOf(1779189206000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Seat");
    _jspx_imports_classes.add("model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setAttribute("pageTitle", "Seat Management");
    List<Seat> seats = (List<Seat>) request.getAttribute("seats");
    if (seats == null) {
        seats = java.util.Collections.emptyList();
    }

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

    String pageTitle = (String) request.getAttribute("pageTitle");
    if (pageTitle == null || pageTitle.trim().isEmpty()) {
        pageTitle = "Online Movie Ticket Reservation System";
    }
    String message = (String) request.getAttribute("message");
    if (message == null || message.trim().isEmpty()) {
        message = request.getParameter("message");
    }
    User loggedInUser = (User) session.getAttribute("loggedInUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>");
      out.print( pageTitle );
      out.write("</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --sidebar-start: #101828;\r\n");
      out.write("            --sidebar-end: #1f2937;\r\n");
      out.write("            --accent: #f59e0b;\r\n");
      out.write("            --page-bg: #f3f4f6;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            background: linear-gradient(180deg, #f8fafc 0%, var(--page-bg) 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .app-shell {\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 280px;\r\n");
      out.write("            background: linear-gradient(180deg, var(--sidebar-start), var(--sidebar-end));\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar .nav-link {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.82);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin-bottom: 0.35rem;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar .nav-link:hover,\r\n");
      out.write("        .sidebar .nav-link.active {\r\n");
      out.write("            background: rgba(245, 158, 11, 0.18);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .app-card {\r\n");
      out.write("            border: 0;\r\n");
      out.write("            border-radius: 18px;\r\n");
      out.write("            box-shadow: 0 16px 40px rgba(15, 23, 42, 0.08);\r\n");
      out.write("        }\r\n");
      out.write("        .hero-banner {\r\n");
      out.write("            background: linear-gradient(135deg, #0f172a 0%, #1e293b 55%, #334155 100%);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 22px;\r\n");
      out.write("        }\r\n");
      out.write("        .brand-badge {\r\n");
      out.write("            background: rgba(245, 158, 11, 0.16);\r\n");
      out.write("            color: #fbbf24;\r\n");
      out.write("            border: 1px solid rgba(245, 158, 11, 0.28);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"d-flex app-shell\">\r\n");
      out.write("    <aside class=\"sidebar p-4 d-flex flex-column sticky-top align-self-start\" style=\"top: 0; min-height: 100vh;\">\r\n");
      out.write("        <div class=\"mb-4\">\r\n");
      out.write("            <div class=\"badge rounded-pill brand-badge mb-3 px-3 py-2\">SE1020 Project</div>\r\n");
      out.write("            <h4 class=\"fw-bold mb-1\">Online Movie Ticket Reservation System</h4>\r\n");
      out.write("            <p class=\"text-white-50 mb-0\">MVC JSP + Servlet demo</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"nav flex-column\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/jsp/dashboard.jsp\"><i class=\"bi bi-speedometer2 me-2\"></i>Dashboard</a>\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/users?action=list\"><i class=\"bi bi-people me-2\"></i>Users</a>\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/movies?action=list\"><i class=\"bi bi-film me-2\"></i>Movies</a>\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/showtimes?action=list\"><i class=\"bi bi-calendar-event me-2\"></i>Showtimes</a>\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/reservations?action=list\"><i class=\"bi bi-ticket-perforated me-2\"></i>Reservations</a>\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/seats?action=list\"><i class=\"bi bi-view-list me-2\"></i>Seats</a>\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/reviews?action=list\"><i class=\"bi bi-star me-2\"></i>Reviews</a>\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/jsp/login.jsp\"><i class=\"bi bi-box-arrow-in-right me-2\"></i>Login</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"mt-auto pt-4 text-white-50 small\">\r\n");
      out.write("            ");
 if (loggedInUser != null) { 
      out.write("\r\n");
      out.write("                Signed in as <strong class=\"text-white\">");
      out.print( loggedInUser.getName() );
      out.write("</strong>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                Guest session\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </aside>\r\n");
      out.write("    <main class=\"flex-grow-1 p-4 p-lg-5\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            ");
 if (message != null && !message.trim().isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-info border-0 app-card mb-4\">");
      out.print( message );
      out.write("</div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("<div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("    <div>\r\n");
      out.write("        <h2 class=\"fw-bold mb-1\">Seat Management</h2>\r\n");
      out.write("        <p class=\"text-secondary mb-0\">Monitor seat availability by showtime.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <a class=\"btn btn-warning fw-bold\" href=\"");
      out.print( request.getContextPath() );
      out.write("/seats?action=add\">Add Seat</a>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"card app-card\">\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("            <table class=\"table table-hover align-middle mb-0\">\r\n");
      out.write("                <thead class=\"table-light\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>ID</th><th>Showtime</th><th>Seat No.</th><th>Status</th><th>Type</th><th>Price</th><th class=\"text-end\">Actions</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                ");
 for (Seat seat : seats) { 
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print( seat.getId() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( seat.getShowtimeId() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( seat.getSeatNumber() );
      out.write("</td>\r\n");
      out.write("                    <td><span class=\"badge ");
      out.print( "Booked".equalsIgnoreCase(seat.getStatus()) ? "text-bg-danger" : "text-bg-success" );
      out.write('"');
      out.write('>');
      out.print( seat.getStatus() );
      out.write("</span></td>\r\n");
      out.write("                    <td>");
      out.print( seat.getType() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( seat.getPrice() );
      out.write("</td>\r\n");
      out.write("                    <td class=\"text-end\">\r\n");
      out.write("                        <a class=\"btn btn-sm btn-outline-primary\" href=\"");
      out.print( request.getContextPath() );
      out.write("/seats?action=edit&id=");
      out.print( seat.getId() );
      out.write("\">Edit</a>\r\n");
      out.write("                        <a class=\"btn btn-sm btn-outline-danger\" href=\"");
      out.print( request.getContextPath() );
      out.write("/seats?action=delete&id=");
      out.print( seat.getId() );
      out.write("\" onclick=\"return confirm('Delete this seat?')\">Delete</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("(() => {\r\n");
      out.write("    'use strict';\r\n");
      out.write("    const forms = document.querySelectorAll('.needs-validation');\r\n");
      out.write("    Array.from(forms).forEach(form => {\r\n");
      out.write("        form.addEventListener('submit', event => {\r\n");
      out.write("            if (!form.checkValidity()) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                event.stopPropagation();\r\n");
      out.write("            }\r\n");
      out.write("            form.classList.add('was-validated');\r\n");
      out.write("        }, false);\r\n");
      out.write("    });\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
